### PR TITLE
Make Jenkins publish external library

### PR DESCRIPTION
**Pull request by zachlefevre**

### CODE REVIEW

**Review by catstavi — COMMENTED** [review]
normally I think I would expect something that triggers downstream job 'sbt build', but I guess soda-fountain doesn't even use the shared dockerize job? I don't see any problems with this, but I'm also in no way an expert on this jenkins file or soda fountain build procedures. 

Have you tested building this branch in jenkins?

**Comment by zachlefevre** [comment]
@catstavi It does use the shared dockerize job https://github.com/socrata-platform/soda-fountain/blob/zlef%2Fmake_jenkins_publish_external_lib/Jenkinsfile#L169

**Comment by zachlefevre** [comment]
@catstavi and this will kick off the shared sbt build job https://github.com/socrata-platform/soda-fountain/blob/zlef%2Fmake_jenkins_publish_external_lib/Jenkinsfile#L21

**Comment by zachlefevre** [comment]
I haven't tested it directly since doing so would require cutting a release of SF.

**Review by catstavi — APPROVED** [review]
none of the jobs we're trying run take a branch specifier (for easy testing) and also its a pipeline build structure I haven't seen before! so I have no step by steps for testing this job... we can always revert I suppose

**Pull request merged**
