### PR TITLE
Use the right resource scope when querying

### PR DESCRIPTION
**Pull request by rjmac**
So responses don't get cut off in the middle.

### CODE REVIEW

**Comment by cyranix** [comment]
Is there any test we can add to guard against regression?

**Comment by AEscobarCruz** [comment]
@cyranix pretty sure there is a cheetah test that could be written out.

**Comment by rjmac** [comment]
Cheetah is the right place for that, yeah.

**Comment by AEscobarCruz** [comment]
probably should assign that as a ticket for your group. @chitang, thoughts?

**Comment by AEscobarCruz** [comment]
:shipit: tested it locally, as soon as pending tests are done, think we can roll this out.

**Comment by chitang** [comment]
Yes, nbego team should create a test to cover that.  Joe has been working with larger data.  He may already have something close to ready.

**Pull request merged**
