### PR TITLE
Krah/spandex error message

### PR DESCRIPTION
**Pull request by sokrahta**
I thought maybe we should give a better error message than "null" when soda-fountain couldn't get a spandex response for some reasons.

### CODE REVIEW

**Comment by urmilan** [comment]
We should be consistent with the rest of soda-fountain and use `SodaUtils.errorResponse` (should be plenty of examples elsewhere in the project).

**Comment by sokrahta** [comment]
no need for a new error case class, I'll just leverage InternalException

**Comment by sokrahta** [comment]
actually InternalException isn't cooperating with the socrata-http exceptions, so I'm creating a new case class

**Comment by urmilan** [comment]
:shipit:

**Pull request merged**
